export const GET_ALL_TASK = "GET_ALL_TASK";
export const GET_ALL_TASK_SUCCESS = "GET_ALL_TASK_SUCCESS";
export const GET_ALL_TASK_FAILURE = "GET_ALL_TASK_FAILURE";
export const GET_DATA_PAGINATION = "GET_DATA_PAGINATION";
export const GET_DATA_PAGINATION_SUCCESS = "GET_DATA_PAGINATION_SUCCESS";
export const GET_DATA_PAGINATION_FAILURE = "GET_DATA_PAGINATION_FAILURE";
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE";
export const SEARCH_TASK = "SEARCH_TASK";
export const SEARCH_TASK_SUCCESSS = "SEARCH_TASK_SUCCESSS";
export const SEARCH_TASK_FAILURE = "SEARCH_TASK_FAILURE";
export const CHECK_DONE = "CHECK_DONE";
export const CHECK_DONE_SUCCESS = "CHECK_DONE_SUCCESS";
export const CHECK_DONE_FAILURE = "CHECK_DONE_FAILURE";

// User
export const GET_ALL_DATA_USER = "GET_ALL_DATA_USER";
export const GET_ALL_DATA_USER_SUCCESS = "GET_ALL_DATA_USER_SUCCESS";
export const GET_ALL_DATA_USER_FAILURE = "GET_ALL_DATA_USER_FAILURE";
export const GET_ALL_DATA_USER_LOADING = "GET_ALL_DATA_USER_LOADING";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const CHECK_LOGIN_SUCCESS = "CHECK_LOGIN_SUCCESS";
export const CHECK_LOGIN_FAILURE = "CHECK_LOGIN_FAILURE";
export const CHECK_LOGOUT = "CHECK_LOGOUT";
export const CHECK_LOGOUT_SUCCESS = "CHECK_LOGOUT_SUCCESS";
export const CHECK_LOGOUT_FAILURE = "CHECK_LOGOUT_FAILURE";

export const OPEN_LOADING = "OPEN_LOADING";
export const CLOSE_LOADING = "CLOSE_LOADING";

// Error
export interface MessageError {
    message: string;
}
